### ISSUE TITLE
one bug I met. When I try ./initialize.sh under the environment I met the following error

### ISSUE THREAD

**Issue by Ai-is-light** [FORTH-ModelBasedTracker/MocapNET#1]
thanks for your excellent work

**Comment by Ai-is-light** [comment]
MocapNET/AmmarServer/src/Services/APushService/device.c:7:18: error: missing binary operator before token "("
 #if __has_include("configuration.h") && __has_include(<stdint.h>)
                  ^
make[2]: *** [AmmarServer/src/Services/APushService/CMakeFiles/apushservice.dir/device.c.o] Error 1
make[1]: *** [AmmarServer/src/Services/APushService/CMakeFiles/apushservice.dir/all] Error 2
make: *** [all] Error 2

thx for this excellent work.
Looking forward to any replies

**Comment by Ai-is-light** [comment]
I used CentOS7

**Comment by AmmarkoV** [comment]
Hello this has to do with a secondary project I am using ( https://github.com/AmmarkoV/AmmarServer/ ) in order to make a MocapNET webservice as a demo ( https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/MocapNETHTTP ) , I will disable it since
A) it is currently not yet working
B) until it is working it will only cause confusion..! 

Thank you for your feedback!

**Comment by AmmarkoV** [comment]
You can remove the AmmarServer directory from MocapNET root, I disabled the HTTP server with commit https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/98a7f93890bc6f2acfa4d9b9cd833218f60025ee so it wont cause any compilation problems any more..

**Comment by Ai-is-light** [comment]
thanks, I will try
