### ISSUE TITLE
The CSV cluster plot utility generats nothing

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [FORTH-ModelBasedTracker/MocapNET#103]
I run the following command to use the CSV cluster plot utility.
```
./CSVClusterPlot
```
But it generats nothing as the below image.

![Screenshot from 2023-07-25 04-42-48](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/23301778/efb0b7a1-2bea-4ca5-a86f-7e553e99f23b)

**Comment by AmmarkoV** [comment]
This problem ( like https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/106 and https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/96 ) is caused by the FORTH network not allowing access to the ground truth files 
I will now also upload these files on a google drive and update the initialize script to download them from there

**Comment by AmmarkoV** [comment]
Dear Ishihara,

Please git pull
rerun the ./initialize.sh script choosing Y when asked to download the CMU BVH datasets

After that instead of getting console output like what you show, which is : 

![screen-2023-07-25-12-20-51](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/97630/a7e03763-e58a-48e8-be69-dd70e3cd02f4)

You should be getting console output like : 

![screen-2023-07-25-12-21-48](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/97630/af3ccc7c-59cb-49cc-8b47-cc1aff290109)

and a projection plot like : 

![screen-2023-07-25-12-22-03](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/97630/84486101-a8ec-4596-8ac9-e685d6abcdf6)
