### ISSUE TITLE
Using only the 2D-to-3D lifting module with my own 2D pose estimator

### ISSUE THREAD

**Issue by Stack-it-up** [FORTH-ModelBasedTracker/MocapNET#107]
Hello, 

I have a 2D pose estimator that works decently in my setup and I would like to use it in place of the 2D pose estimator provided in this repo: do you have any suggestions on how to do it? It seems pretty straightforward, I have to dump all the heatmaps into a CSV file like the function ``dumpHeatmapToCSVFile`` from https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/JointEstimator2D/jointEstimator2D.cpp

However, the details are not clear to me: how should I initialize the ``struct JointEstimator2D``? 

Thank you for the awesome repository.

**Comment by AmmarkoV** [comment]
Hello! 
Thank you for your kind words!

There are two ways to do what you want, the easy off-line one, the harder on-line one  : 

1) The easy off-line one  :

Use this [CSV File](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/dataset/sample.csv)  as a guide and print out your 2D joint estimator output in CSV format! You can then use something like 
 `MocapNET2CSV --from yourFile.csv --show 3`  
and immediately test your output.


The only thing that you should be careful with is that the 2D joints you provide should be normalized and should have an aspect ratio of 1920:1080 = 1.7777.. This is a very common pitfall, the next python code should do this conversion in the  "correct"  way  if you give it each X,Y coordinate you extract and your image width,height 

``` 

"""
 This is a VERY commonly needed conversion, MocapNET is trained on a 1920x1080 frame to match popular cameras,
 many image sources/sensors produce different kinds of image resolutions. The aspect ratio is very important
 for good results, this function does the needed conversion..
"""
def transform_coordinate_wrt_target(x, y, width, height, targetWidth = 1920, targetHeight = 1080):
    aspect_ratio = width / height

    if aspect_ratio > targetWidth / targetHeight:
        # The image is wider than the frame
        scaled_width = targetWidth
        scaled_height = int(targetWidth / aspect_ratio)
        offset_x = 0
        offset_y = (targetHeight - scaled_height) // 2
    else:
        # The image is taller than the frame
        scaled_width = int(targetHeight * aspect_ratio)
        scaled_height = targetHeight
        offset_x = (targetWidth - scaled_width) // 2
        offset_y = 0
        
    new_x = (x / width) * scaled_width + offset_x
    new_y = (y / height) * scaled_height + offset_y
    return new_x, new_y
```


2) The harder on-line one : 


The hard way to do it (for real-time operation) would be to basically replace the src/JointEstimator2D with your pose estimator.

What you want to do is 
put your 2D estimations inside the 
                    struct Skeletons2DDetected skeleton2DEstimations= {0}; 

as seen here :
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNET2LiveWebcamDemo/livedemo.cpp#L238C78-L238C92

The documentation for the skeleton2DEstimations is the following :

```
/**
 * @brief A C struct to hold a 2D coordinate
 */
struct point2D
{
    float x,y;
};

/**
 * @brief A C struct to hold a 3D coordinate
 */
struct point3D
{
    float x,y,z;
};


/**
 * @brief A structure to hold a bounding box
 */
struct boundingBox
{
    char populated;
    float minimumX;
    float maximumX;
    float minimumY;
    float maximumY;
};


/**
 * @brief A C struct to hold a hand. It contains its 2D points, its 3D points and some flags that signal
 */
struct handCOCO
{
    int isPopulated;
    int isLeft;
    int isRight;

    struct point2D joint2D[COCO_HAND_PARTS];
    float  jointAccuracy[COCO_HAND_PARTS];
    unsigned int active[COCO_HAND_PARTS];
    struct point3D joint[COCO_HAND_PARTS];
};

/**
 * @brief A C struct to hold a hand. It contains its 2D points, its 3D points and some flags that signal
 */
struct headOP
{  
    int isPopulated;
    struct point2D joint2D[OP_HEAD_PARTS];
    float  jointAccuracy[OP_HEAD_PARTS];
    unsigned int active[OP_HEAD_PARTS];
    struct point3D joint[OP_HEAD_PARTS];
};


/**
 * @brief A C struct to hold a body. It contains its 2D points, its 3D points and some flags that signal
 */
struct body25OP
{  
    int isPopulated;
    struct point2D joint2D[BODY25_PARTS]; 
    struct point2D bbox2D[2];
    
    float  jointAccuracy[BODY25_PARTS];
    unsigned int active[BODY25_PARTS];
    struct point3D joint[BODY25_PARTS];
    struct point3D bbox[8];
};



/**
 * @brief A C struct to hold a skeleton. It contains its 2D points, its 3D points and some flags that signal
 */
struct skeletonStructure
{
    unsigned int observationNumber , observationTotal;
    unsigned int userID;
    unsigned int totalUsersPresent; 
    //------------------------
    struct body25OP body;
    struct handCOCO leftHand;
    struct handCOCO rightHand;
    struct headOP head;
    //------------------------
    struct boundingBox  bbox2D;
};


struct Skeletons2DDetected
{ 
   unsigned int numberOfSkeletonsDetected;
   struct skeletonStructure skeletons[16];
};

```

The original files that hold it along with joint orders etc are  here :
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/IO/commonSkeleton.hpp
and here :
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/JointEstimator2D/jointEstimator2D.hpp


Once again keep in mind the normalization under the specific 1920:1080 aspect ratio, C code to do this exists here : 

https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/JointEstimator2D/jointEstimator2D.cpp#L554



I hope this provides you with enough help,
If you encounter more problems (or success :D ) don't hesitate to ask 
Hope your experiments go well!

PS : 

Due to the "complexity" of writing/linking against so many libraries etc, the next and final mocapnet version ([sneak peek here ](https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/mnet4/src/python/mnet4) :P )  is implemented in python so you would be able to just create a python dict , however at the time of writing this this is not ready yet :S
