### ISSUE TITLE
Could not find COCO 2D skeleton

### ISSUE THREAD

**Issue by delebash** [FORTH-ModelBasedTracker/MocapNET#15]
I ran openpose with just the face option.  When trying to convert to bvh I get error Could not find COCO 2D skeleton in json/colorFrame_0_000000000000_keypoints.json

**Comment by AmmarkoV** [comment]
Hello again , :)
The colorFrame_0_000000000000 is my internal naming scheme for the OpenPose output 
This is an example dataset you can use to browse how I organize OpenPose data http://ammar.gr/datasets/shuffle.webm-data.tar.gz 

Looking at the dataset  above and also reading the text in the conversion utility https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/Converters/convertBody25JsonToCSV.cpp#L2 you will fully understand!

In any case (and long made short) due to OpenPose skipping frames if it is given a video, I dump the video I want to process in jpg files first ( colorFrame_0_xxxxx.jpg ) I then give openpose the jpeg files as input ( so it is forced to process every one of them without skipping any or losing the correspondence because of different decoding framerates etc ). Then finally MocapNET receives the path and looks at this colorFrame_0_xxxx pattern by default..

This is the script I use for converting video files to jpg files
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/dump_video.sh

This is a slightly modified script to help you make your own for converting the jpg files to JSON files that will be automatically picked up by MocapNET
https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/processDatasetWithOpenpose.sh 

If you didn't manage to process your data or still have questions do let me know!

I will also update the README so that it points to the documentation inside the utility it gives a little more information

**Comment by delebash** [comment]
AmmarkoV 
Thank you very much for the help.  I actually found the problem that was causing my error. Please refer to issue https://github.com/FORTH-ModelBasedTracker/MocapNET/issues/17

Thanks
