### ISSUE TITLE
cmakelist error 1

### ISSUE THREAD

**Issue by sohail759** [FORTH-ModelBasedTracker/MocapNET#19]
nvidia@nvidia-desktop:~/Desktop/CONVSYS/MocapNET-master$ ./initialize.sh
Generating shortcut
CMU BVH datasets appear to have been downloaded..
mkdir: cannot create directory ‘combinedModel’: File exists
mkdir: cannot create directory ‘mode3’: File exists
mkdir: cannot create directory ‘mode5’: File exists
Downloading Models for mode 3/quality setting 1.0
mkdir: cannot create directory ‘1.0’: File exists
Downloading Models for mode 3/quality setting 2.0
mkdir: cannot create directory ‘2.0’: File exists
Downloading 2D Joint Estimator models
Found a local tensorflow installation, not altering anything
RGBDAcquisition appears to already exist ..
AmmarServer appears to already exist ..
Now to try and build MocapNET..
mkdir: cannot create directory ‘build’: File exists
CMake Error: The current CMakeCache.txt directory /home/nvidia/Desktop/CONVSYS/MocapNET-master/build/CMakeCache.txt is different than the directory /home/nvidia/Desktop/MocapNET-master/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/nvidia/Desktop/CONVSYS/MocapNET-master/CMakeLists.txt" does not match the source "/home/nvidia/Desktop/MocapNET-master/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
CMake Error: The source directory "/home/nvidia/Desktop/MocapNET-master" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:272: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
#####################################################################
i am getting this error while running initialize.sh ,please recommend some solution

**Comment by AmmarkoV** [comment]
Hello due to the multiple "exists" prompts of the initialize script, I suppose that the initialize script has already run once and downloaded all required things, so the actual problem is the CMake building procedure..
Reading the CMake output 
The source "/home/nvidia/Desktop/CONVSYS/MocapNET-master/CMakeLists.txt" does not match the source "/home/nvidia/Desktop/MocapNET-master/CMakeLists.txt" used to generate cache it appears that that you first did a build in the /home/nvidia/Desktop/MocapNET-master/CMakeLists.txt and then moved the project to the /home/nvidia/Desktop/CONVSYS/MocapNET-master/CMakeLists.txt and thats why CMake is complaining, because the new build has a mismatch with the directories it cached during its original run..

The solution is to create a new build directory so basically I think the following should work..

```
cd /home/nvidia/Desktop/CONVSYS/MocapNET-master/
mv build buildBROKEN
mkdir build
cd build 
cmake .. 
make 
cd ..
```

**Comment by AmmarkoV** [comment]
Also if you pull the latest master version the initialize script will automatically replace the build directory with a new one, probably solving your issue..

**Comment by sohail759** [comment]
Thanks alot for your help.can u please send me the link of updated one.
Regards

**Comment by AmmarkoV** [comment]
https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/initialize.sh
