### ISSUE TITLE
Upper body pose estimation

### ISSUE THREAD

**Issue by shichaog** [FORTH-ModelBasedTracker/MocapNET#25]
Hey @AmmarkoV @padeler @nkyriazis ,
Pleased to see this amazing work.
I need a help from you.
I changed int MAXIMUM_NUMBER_OF_NSDM_ELEMENTS_MISSING=110 to value 133 for upper body estimation, but the estimation results is not good.
Would you help update a new model or how can I train a new model for upper body estimation.
Thanks!

**Comment by AmmarkoV** [comment]
Dear @shichaog  the new version of MocapNET that is ready and is pending review for publication already does what you request! So I don't need to train a new model :)  MocapNET2 is natively split in upper and lowerbody parts so even in the presence of severe occlusions (i.e. all the lower body missing) you are able to still get a good estimation for the upperbody. 

Unfortunately I am unable to publish it and upload the code and pretrained models in this repository until we get the peer-review results from the conference it is submitted at.. :(  

[Best I can do is give you a preview of a raw run of the new version](http://ammar.gr/mocapnet/mnet2/sept2020version.mp4)

Now to explain the MAXIMUM_NUMBER_OF_NSDM_ELEMENTS_MISSING logic.  The NSDM matrices have the following design :

![image](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/figureA.png)

![image](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/figureB.png)

The MAXIMUM_NUMBER_OF_NSDM_ELEMENTS_MISSING is set to 110 as a safeguard since each joint missing removes one raw and one column of the NSDM matrix. The problem is that after some critical threshold the input matrix to the neural network becomes so sparse and different from the training set that the neural network is not able to derive a solution with it..

The best thing I can suggest with the current version of MocapNET currently available is to use the  "--remember" flag that fills in some occlusions by [populating the previous remembered value](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLiveWebcamDemo/mocapNETLiveDemo.cpp#L989)  by using the [fillInTheBlanks](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/mocapnet.cpp#L29) call. 

One could also create "fake legs" when legs are completely occluded that are just 4 vertical 2d points if you only have an upperbody..  However these are simple workarounds that do not solve the problem.  As your request correctly suggests the upper/lower matrix split  is a much better strategy to combat lower body occlusions.  I apologise for the inconvinience of having to wait and it is just as frustrating to me having done all this work in 2020 and just waiting to publish the code, however thats how the academic enviornment works.!

**Comment by shichaog** [comment]
@AmmarkoV Thanks for your patient explanation and excellent work. I'll try your suggestions, but as well  I'm looking forward to the publish date.

**Comment by AmmarkoV** [comment]
Upper/Lower body pose estimation [has been implemented and is now available](https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/5e0c8d41e7afba7266cba0e239abe40a51aad950)
