### ISSUE TITLE
OpenGL can not visualization

### ISSUE THREAD

**Issue by FrankYoungchen** [FORTH-ModelBasedTracker/MocapNET#27]
hi,bro,I want to use OpenGL visualization to render a skinned mesh
`./MocapNETLiveWebcamDemo --from shuffle.webm --openpose --opengl --frames 375`
I try to change ENABLE_OPENGL to on during compilation and using the --opengl flag when running the MocapNETLiveWebcamDemo 
But I can not  see the experimental OpenGL visualization

**Comment by merltron** [comment]
I had same problem a week ago...I updated `build/CMakeCache.txt` and changed the line `ENABLE_OPENGL:BOOL=OFF` to `ENABLE_OPENGL:BOOL=ON`. After compiling again, it worked with the command you mentioned. Not sure why I had to change the CMakeCache but at least it worked.

**Comment by AmmarkoV** [comment]
Hello guys,  I typically use cmake-gui to set/unset the variables ( sudo apt-get install cmake-qt-gui )

![screen-2020-10-10-15-43-15](https://user-images.githubusercontent.com/97630/95655359-601f2180-0b0f-11eb-93ed-1a9d228d2e03.jpg)

So inside the build directory if you "cmake-gui .."  you will bring up the menu of the screenshot above where you can enable the openGL code ( ENABLE_OPENGL flag ) then click configure and then generate to refresh the CMake stuff and then build by using make..!

@FrankYoungchen  if you still cant run it after using the above suggestion please send me again so we can debug this :) 


Maybe too much information but in order to better understand the OpenGL code : 

If you are interested in the OpenGL stuff the code in this repository uses [my haphazard OpenGL renderer under the hood](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer)

The renderer is "scriptable" and loads [scenes from files like these](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Scenes), and the scene you see is stored in [dataset/human3D.conf](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/dataset/human3D.conf)

The [rendered model used in MocapNET](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/dataset/human3D.conf#L39) has been created using [makehuman](http://www.makehumancommunity.org/) 
I then export the makehuman model with [this rig](http://www.makehumancommunity.org/content/cmu_plus_face.html) as an OpenCollada model

This is converted to a [.TRI format](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/ModelLoader/model_loader_tri.c) using [this Assimp dumper](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/submodules/Assimp)

**Comment by AmmarkoV** [comment]
Please note that after the [upgrade to Mnet2](https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/5e0c8d41e7afba7266cba0e239abe40a51aad950) a lot of stuff has changed.. OpenGL code is still in experimental status, hopefully it will work for you..

**Comment by FrankYoungchen** [comment]
thanks! I debug it and I find that My opengl is not installed well

**Comment by AmmarkoV** [comment]
Ok :)
In ubuntu typically doing sudo apt-get install freeglut3-dev libglew-dev mesa-utils you can get the "minimum" gl stuff
If you try running glxgears and you see the gears spinning it means that X-Server can properly render.

If you want standalone OpenGL stuff to test if you check inside dependencies//RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/System

In [this directory](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/System
) I have some testOpenGL3* scripts you can try to use to make minimal tests, you might find them useful

**Comment by AmmarkoV** [comment]
Also maybe the new BVHGUI2 is a good way to test the OpenGL stuff

![BVHGUI](https://raw.githubusercontent.com/FORTH-ModelBasedTracker/MocapNET/master/doc/BVHGUI2.jpg)


```
./BVHGUI2 --opengl
```
