### ISSUE TITLE
Tensorflow/Keras code for training on custom dataset

### ISSUE THREAD

**Issue by whitealex95** [FORTH-ModelBasedTracker/MocapNET#41]
Hi, I want to use your mocap net architecture on my custom dataset.
Your paper says that you trained the model using the tensorflow/keras, but I have hard time finding out how the network architecture is actually created.
Is the training part of the code (data preprocessing / ensemble / SNN network architecture / lr scheduling, etc) available?
Thanks alot

**Comment by AmmarkoV** [comment]
Hello, due to limitations imposed by [FORTH](https://www.ics.forth.gr/) the training code is not and will not be available, we are just publishing the demo and the pretrained networks used in the paper under [this](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/license.txt) license. This is not my decision and not my fault, its institute policy :( 

The ensemble architecture is thoroughly explained in the papers [1](http://users.ics.forth.gr/~argyros/mypapers/2021_01_ICPR_Qammaz.pdf) and [2](http://users.ics.forth.gr/~argyros/mypapers/2019_09_BMVC_mocapnet.pdf)

The [dataset used](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh#L89) as well as the [GroundTruthGenerator utility](https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/src/GroundTruthGenerator) used to create the training datasets are also included.
 
You can use [netron](https://github.com/lutzroeder/netron) to open the .pb files and take a peek in their internal organization.

Given all these "ingredients" one could make his own homebrew MocapNET..
