### ISSUE TITLE
MocapNET2CSV to bvh worked, but got some errors

### ISSUE THREAD

**Issue by xamxixixo** [FORTH-ModelBasedTracker/MocapNET#45]
Hello,

So I ran the MocapNET2CSV (from JSON files exported by Openpose). It worked and I had the out.bvh file. But the output animation is not completely right compared to the Openpose preview output. The body suddenly turned around 180 degrees and its position was lifted higher, just one time, then back to normal.

When I looked at the output log I saw some errors:

`Failed @ loadCalibration (null) , color.calib`
```
Loading Pose 0 -> dataset/poses/neutral.bvh  : Pose 0 -> dataset/poses/neutral.bvh  is corrupted
Failure
Loading Pose 1 -> dataset/poses/tpose.bvh  : Pose 1 -> dataset/poses/tpose.bvh  is corrupted
Failure
Loading Pose 2 -> dataset/poses/x.bvh  : Pose 2 -> dataset/poses/x.bvh  is corrupted
Failure
Loading Pose 3 -> dataset/poses/handsup.bvh  : Pose 3 -> dataset/poses/handsup.bvh  is corrupted
Failure
Loading Pose 4 -> dataset/poses/leftwave.bvh  : Pose 4 -> dataset/poses/leftwave.bvh  is corrupted
Failure
Loading Pose 5 -> dataset/poses/rightright.bvh  : Pose 5 -> dataset/poses/rightright.bvh  is corrupted
Failure
Loading Pose 6 -> dataset/poses/leftleft.bvh  : Pose 6 -> dataset/poses/leftleft.bvh  is corrupted
Failure
Loading Pose 7 -> dataset/poses/push.bvh  : Pose 7 -> dataset/poses/push.bvh  is corrupted
Failure
Loading Pose 8 -> dataset/poses/rightwave.bvh  : Pose 8 -> dataset/poses/rightwave.bvh  is corrupted
Failure
Failed to read recognized Poses
This is not fatal, but poses/gestures will be deactivated..
```

Are they errors that made the animation of out.bvh wrong? If so, how to fix?

Thank you.

**Comment by AmmarkoV** [comment]
Hello these are parts of the [gesture recognition engine](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETLib2/mocapnet2.cpp#L405) which are just an experimental feature..
The problem stems from the [gestures recorded](https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/dataset/gestures) no longer corresponding to the [main bvh file](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/dataset/headerWithHeadAndOneMotion.bvh),

As stated in the output this is not a problem and will not effect 2D -> 3D functionality.

In any case its good you opened the issue so that I reduce needless console output spam

**Comment by AmmarkoV** [comment]
The messages won't be generated now except if a user explicitly calls the application using the --gestures which however is not currently working and will correctly give the error messages until the gesture bvh files are updated..
