### ISSUE TITLE
Installation stops at 11% (Windows + Cygwin64)

### ISSUE THREAD

**Issue by BibaDev** [FORTH-ModelBasedTracker/MocapNET#47]
Hi all, I need help, I can't install MocapNET

I am using Windows + Cygwin64

Installed all the packages, but everything breaks at 11% what to do?

![image](https://user-images.githubusercontent.com/59769710/103437391-379f5300-4c38-11eb-9e96-2d485dcf3f3e.png)

**Comment by AmmarkoV** [comment]
Hello, Cygwin or building directly on windows has never been tested and is not supported..
The C/C++ code of the repository is pretty portable and "vanilla" however the error you are getting  in bvh_loader.c:18 is actually the 
```
#include <stdio.h>
```
https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/MotionCaptureLoader/bvh_loader.c#L18

which is the most basic include you can do..

People have reported MocapNET working on windows using the [Linux subsystem](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q?rtc=1&activetab=pivot:overviewtab) so if you want to use windows I suggest taking this route..!

**Comment by AmmarkoV** [comment]
Since this issue is stale and there are no plans for Cygwin compatibility I am closing the issue,
If you want to use windows please consider using the [Linux](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q?rtc=1&activetab=pivot:overviewtab) subsystem provided by Microsoft..!

Of course using the native Linux version is always the best choice! :)
