### ISSUE TITLE
how can i get the results of a video containing 2d,3d coordinations?

### ISSUE THREAD

**Issue by TonyFaith** [FORTH-ModelBasedTracker/MocapNET#5]
thanks for this wonderful work, i an wondering how could i get the 2d and 3d pose coordinates? at the same time, how can i save the result video showed as --visualize flag?

**Comment by AmmarkoV** [comment]
Hello! 
I just added the features you requested..!
After running the MocapNETLiveWebcamDemo **without** the --live flag you will see two files appear in the directory besides the out.csv . The one is in.csv and it is a CSV file with the 2D inputs, the second is out3DP.csv which is a CSV file with the 3D Points output , the first row of the out3DP.csv file will currently be wrong but you have all of the information there. I will fix it in a subsequent commit.
Finally in order to store the 3D visualization use the --save3D flag.! If you want to get rid of things like the text there consider commenting out things from here -> https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNETLib/visualization.cpp#L1094 ( i.e. the cv::putText calls! )
Have fun!

**Comment by AmmarkoV** [comment]
Happy 2020. Since it appears that you don't have a further comment I will close this issue. Feel free to open another one..
