### ISSUE TITLE
Missing "handsup.bvh"

### ISSUE THREAD

**Issue by mulkkyul** [FORTH-ModelBasedTracker/MocapNET#6]
Hello. Thank you for sharing the excellent work!
I was converting openpose json to bvh 
and I noticed that "handsup.bvh" is missing in the dataset directory .
(Still, conversion seems successful without it.)
Thanks!

**Comment by AmmarkoV** [comment]
Hello, 
You are right! 

I see there is a [forgotten handsup.bvh](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/gestureRecognition.hpp#L27) from a previous version here.. I will update the header.

The gesture recognition is a very small and simple part of the codebase. Of course gesture recognition is not essential for 3D pose estimation ([it is not even mentioned in the paper](http://users.ics.forth.gr/~argyros/mypapers/2019_09_BMVC_mocapnet.pdf)) and instead is just an experimental add-on.  The final goal of this particular code segment is to be able to observe a person and "catch" specific gestures that the person does as seen here -> http://ammar.gr/mocapnet/mocapnetGestures.ogv

That being said this gesture code segment is very experimental and that's why it is also disabled by default currently.

Hopefully in one of the next iterations of the library it will be able to recognize the following gestures :  
https://github.com/FORTH-ModelBasedTracker/MocapNET/tree/master/dataset/gestures

**Comment by AmmarkoV** [comment]
I added the forgotten gesture with commit https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/5316549833ca3d4e4ba9d09fd35e7317a0e9a20b
