### ISSUE TITLE
Branch mnet3 build MocapNetLib2 occur error caused by missing files in NDSM

### ISSUE THREAD

**Issue by rivergold** [FORTH-ModelBasedTracker/MocapNET#66]
On branch mnet3, `src/MocapNET2/MocapNETLib2/CMakeLists.txt` needs files 

```shell
../MocapNETLib2/NSDM/generated_rhand.hpp
../MocapNETLib2/NSDM/generated_lhand.hpp
```
but these files do not appear in NSDM. This will cause the compilation to fail.

**Comment by ChienYuLu** [comment]
Same issue here.
It seems that lots of file listed in [https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/MocapNET2/MocapNETLib2/CMakeLists.txt#L14](url) are missing now. The missing file are following:
`../MocapNETLib2/NSDM/generated_rhand.hpp
../MocapNETLib2/NSDM/generated_lhand.hpp
../MocapNETLib2/visualization/drawHands.cpp
../MocapNETLib2/solutionParts/rightHandSym.cpp
../MocapNETLib2/solutionParts/rightHand.cpp
../MocapNETLib2/solutionParts/leftHand.cpp
../MocapNETLib2/solutionParts/face.cpp`

**Comment by ChienYuLu** [comment]
Same issue here.
It seems that lots of file listed in [src/MocapNET2/MocapNETLib2/CMakeLists.txt:14](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/mnet3/src/MocapNET2/MocapNETLib2/CMakeLists.txt#L14) are missing now. The missing file are following:
```
../MocapNETLib2/NSDM/generated_rhand.hpp
../MocapNETLib2/NSDM/generated_lhand.hpp
../MocapNETLib2/visualization/drawHands.cpp
../MocapNETLib2/solutionParts/rightHandSym.cpp
../MocapNETLib2/solutionParts/rightHand.cpp
../MocapNETLib2/solutionParts/leftHand.cpp
../MocapNETLib2/solutionParts/face.cpp
```

**Comment by AmmarkoV** [comment]
Hello, thanks for reporting this I will check this, it is probably things that I forgot to commit!

**Comment by AmmarkoV** [comment]
I just tried deploying the mnet3 on a fresh laptop and code seems to compile!

![screen68](https://user-images.githubusercontent.com/97630/147344853-42853777-6b87-4b25-8e89-a74f5e1c03cf.jpg)

Sorry for the missing files ( and the general lacking state of the mnet3 branch .. :(  ) 

I am closing the issue since it is fixed, if you encounter more problems please make a new issue, I will monitor these throughout the holidays and try to address them asap..
