### ISSUE TITLE
Could use another BVH hierarchy

### ISSUE THREAD

**Issue by HamzaKhalloufi** [FORTH-ModelBasedTracker/MocapNET#67]
Hi,

I want to use another BVH hierarchy but I get an error say that the expected joints number is different to ours.
I see that you define the **bvhHeader** in **[bvh.hpp](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/301aa3eb3fe00623d61907e93d0a412f984ec082/src/MocapNET2/MocapNETLib2/IO/bvh.hpp#L17)**, I don't know if I change it (the bvhHeader) that will be work or I have to edit other files.

Thank you.

**Comment by AmmarkoV** [comment]
Hello!
Changing the BVH file through bvh.hpp is going to be very difficult and since this is assumed to have a particular order in all modules of the project ( the neural networks etc ) it is most likely going to cause bugs if changed..!

I think your best bet is :

A) to use an external tool like Blender to retarget the BVH output armature to another BVH..!

B) You could probably write your own header/function to do the conversion / file saving
for example you could have hamzaBVH.hpp where you declare your own joint series and then add some code to convert from the MocapNET bvh to your..
