### ISSUE TITLE
the unit of Error metrics 

### ISSUE THREAD

**Issue by KhalloufiHamza** [FORTH-ModelBasedTracker/MocapNET#76]
Hi,
My question is about [your python utility](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py) to compare between H36M MPJPE and your output.
What is the unit of error metrics there (including MPJPE)? the meter or millimeter or something else?
Thank you so much.

**Comment by AmmarkoV** [comment]
Hello!
The measurements are in millimeters, I will add this information the python utility because the way it is currently done it is not explicitly written as you say!

Btw this is how the csv file output while using the tool looks like

![screen-2022-03-18-15-15-18](https://user-images.githubusercontent.com/97630/159009516-b48b6a36-076e-4a0b-b39e-048a7d1813d5.jpg)

**Comment by AmmarkoV** [comment]
Oh and by the way there is a way to change it from millimeters to let's say meters by modifying the [ourScaleX,ourScaleY,ourScaleZ](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py#L337) parameters..
For example using [--ourscale 0.001 0.001 0.001](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/python/compareUtility/compareUtility.py#L347) should make the numbers become meters.. although most 3D pose estimation works deal with millimeter accuracy..

**Comment by KhalloufiHamza** [comment]
thank you a lot Mr. Ammar this is very helpful. 👍
