### ISSUE TITLE
What do we change to make it work on images?

### ISSUE THREAD

**Issue by tasinislam21** [FORTH-ModelBasedTracker/MocapNET#78]
I understand that this code only works on videos. How can we change the code so that it also works on images? 
Thanks

**Comment by AmmarkoV** [comment]
Hello,
the easiest way I can think of is to 
remove the OpenCV code [here](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNET2LiveWebcamDemo/livedemo.cpp#L91) that gets a cv::Mat from the capture device and replace it 
with frame = imread("YourImage.png") check here for documentation on [imread](https://docs.opencv.org/3.4/d4/da8/group__imgcodecs.html)

**Comment by AmmarkoV** [comment]
I have added a "half baked" mode from jpg/png images..

Look at the changes I did here..
https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/c2217938bf42c0a95e3c57bcc6427e9f74049119

basically when running ./MocapNET2LiveWebcamDemo if your --from arguments points to an .jpg or .png file it should use it instead of the camera..

**Comment by AmmarkoV** [comment]
If you try 

```
./MocapNET2LiveWebcamDemo --from dataset/test.jpg --show 3 --cpu
```

you should get something like this now..

![screen-2022-04-12-15-27-03](https://user-images.githubusercontent.com/97630/162962290-c5c9dcec-f172-4ab2-830c-6c3e8193a140.jpg)

**Comment by tasinislam21** [comment]
Thank you very much!!!!

**Comment by AmmarkoV** [comment]
No problem, have fun! 
Closing the issue!
