### ISSUE TITLE
How to convert my private 3D data to BVH building trainning dataset.

### ISSUE THREAD

**Issue by CMsmartvoice** [FORTH-ModelBasedTracker/MocapNET#84]
We would like to train this model using our own 3d data. 
Can you provide some tools to help us convert 3d data to bvh.

**Comment by AmmarkoV** [comment]
Hello, 
Unfortunately due to licensing issues by FORTH which is the copyright holder I am not allowed to publish the NN training code :(
They only permitted me to publish the demo/evaluation code.. 

However you can open the .pb tensorflow saved models in datset/combinedModel and study them/retrain them..! 
As for 3D/training data if when running the [./initialize.sh](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/initialize.sh) script you choose to download the CMU/BVH dataset when asked  I have included a [./createRandomizedDataset.sh](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/scripts/createRandomizedDataset.sh) utility/script that will create 2D input / BVH output CSV files in the dataset/ directory which you can use as inputs and outputs to train your own neural network. To add your poses after downloading the [CMU/BVH dataset](http://cvrlcode.ics.forth.gr/web_share/mocapnet/CMUPlusHeadMotionCapture.zip) you can basically add your private 3D data as your own BVH files.
