### ISSUE TITLE
Documentation - Pretrained models

### ISSUE THREAD

**Issue by AmitMY** [FORTH-ModelBasedTracker/MocapNET#9]
Could you please document your pre-trained models, specifically, what they are expecting to get as an input?

I'm looking for a model that can minimally do body and hands, which I did see in your video:
![image](https://user-images.githubusercontent.com/5757359/77408788-e7e64e00-6dc0-11ea-803a-ea13120f1b1a.png)

But also for a model that can do body+hands+face. Do you have something pretrained like that?

**Comment by AmmarkoV** [comment]
Hello, as you mentioned, [the code-base can understand and parse hands and faces](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET1/MocapNETLib/jsonCocoSkeleton.h#L520) coming from the OpenPose 2D pose estimator ( like the illustration you posted ) however as you have also said and noticed the provided pretrained models in this repository only cover the body..! ( the BVH output has the required joints for face and fingers in order to be future-proof but they are currently not populated in this repository ) .. Unfortunately the next version of MocapNET that will address these parts of the body has not yet been published and so the code provided in this repository only covers what is part of the[ BMVC 2019](https://bmvc2019.org/wp-content/uploads/papers/0710-paper.pdf) work.. I actually have pretrained models for what you are asking :) but I will only be able to publish them to this repository after first publishing the revised-method in a conference.. Sorry about that, I am just a PhD student and this is how the academic publishing scheme works..! :(  Hopefully in a few months they may be available..!

The pre-trained models for the body are an ensemble of simple 4 layer dense neural networks that use SeLU activations  and their input is formed  using the [NSDM structure](https://bmvc2019.org/wp-content/uploads/papers/0710-paper.pdf).  The method and models you see in this repository are [thoroughly described](https://bmvc2019.org/wp-content/uploads/papers/0710-paper.pdf) in the paper.
