### ISSUE TITLE
MocapNET2CSV - exclude face output in BVH file.

### ISSUE THREAD

**Issue by aptmess** [FORTH-ModelBasedTracker/MocapNET#95]
Good day!

Currently I am working with MocapNET in topic "OpenPose3D -> 3D BVH format". The problem is that there is no clear documentation for scripts.

For example, I used script `MocapNET2CSV ` with such parameters, that i have found in other repositories:

```bash
./MocapNET2CSV \
    --from "../2dJoints_v1.4.csv" \
    --size 1280 720 \
    --novisualization \
    -output "../1.bvh" \
    --nolowerbody
```

As i see in the [code](https://github.com/FORTH-ModelBasedTracker/MocapNET/blob/master/src/MocapNET2/MocapNETFromCSV/mocapnet2CSV.cpp#L217) there is an option to include/exclude hands and face from output render. I tried options such as `--noface, --nofaces, --noFaces`, but the output is still having face:

![image](https://user-images.githubusercontent.com/43338025/232536597-67d5bf28-911c-4525-8a7e-80a5c71631c8.png)

What is right parameter for exclude face points output and, secondly, maybe the documentation with this params exists and i have not found it? 

Thanks for answer:)

**Comment by AmmarkoV** [comment]
Hello, the BVH output is hardcoded to produce a full rig with a face (since the neural network ensemble is trained this way it is difficult to switch it off) 

To do what you want, you can use the GroundTruthDumper utility included. It can try to merge what BVH channels are available to a different BVH armature ( for example in your case one without a head ) .

I have some [different armatures and profiles here](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions) 

For example assuming you are on the root directory and an **out.bvh**  MocapNET output has just been generated doing :

```
./GroundTruthDumper --from dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions/DAZFriendlyCGSPEED_ZXYAndHandsAxisBigHands.bvh --merge out.bvh dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions//mergeDazFriendlyAndAddHead.profile --setPositionRotation 0 0 0 0 0 0 --bvh remade.bvh
```
will create a remade.bvh that will have a minimal head..

The "headless" armature will look like this.. 

![screen-2023-07-18-11-07-54](https://github.com/FORTH-ModelBasedTracker/MocapNET/assets/97630/4a8c35af-a31b-4386-829f-735fec33dfd2)

Please note that due to the conversion done by GroundTruthDumper being trivial it can have a negative impact on the animation especially if the target BVH armature is much different than the one produced by the neural network.

**Comment by AmmarkoV** [comment]
Since this question has been answered and is stale for many months I am closing it.

**Comment by justinjohn0306** [comment]
> Hello, the BVH output is hardcoded to produce a full rig with a face (since the neural network ensemble is trained this way it is difficult to switch it off)
> 
> To do what you want, you can use the GroundTruthDumper utility included. It can try to merge what BVH channels are available to a different BVH armature ( for example in your case one without a head ) .
> 
> I have some [different armatures and profiles here](https://github.com/AmmarkoV/RGBDAcquisition/tree/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions)
> 
> For example assuming you are on the root directory and an **out.bvh** MocapNET output has just been generated doing :
> 
> ```
> ./GroundTruthDumper --from dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions/DAZFriendlyCGSPEED_ZXYAndHandsAxisBigHands.bvh --merge out.bvh dependencies/RGBDAcquisition/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/Motions//mergeDazFriendlyAndAddHead.profile --setPositionRotation 0 0 0 0 0 0 --bvh remade.bvh
> ```
> 
> will create a remade.bvh that will have a minimal head..
> 
> The "headless" armature will look like this..
> 
> ![screen-2023-07-18-11-07-54](https://private-user-images.githubusercontent.com/97630/254190271-4a8c35af-a31b-4386-829f-735fec33dfd2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDAyNDQsIm5iZiI6MTcwMzAzOTk0NCwicGF0aCI6Ii85NzYzMC8yNTQxOTAyNzEtNGE4YzM1YWYtYTMxYi00Mzg2LTgyOWYtNzM1ZmVjMzNkZmQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyMzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZGU2OTg2ZmY4ZGFmOWExNDY0NDUwZTIxNjkyYjUwZjM0OTEzMjE0MWVjN2NiNjUxNzFkMzNhYmYyMTFhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tG5ThrXYNo5RVsxIlmCZirI2FUGwz3LCynke0J6keq4)
> 
> Please note that due to the conversion done by GroundTruthDumper being trivial it can have a negative impact on the animation especially if the target BVH armature is much different than the one produced by the neural network.

Can we do the same with the mnet4 branch?
